# Generated by Django 3.0.3 on 2020-02-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='lowercase',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='password',
            name='uppercase',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
